data:
  processed_path: "data/processed/"
  processed_train_df: "train_df_praticagem.csv"
  processed_test_df: "test_df_praticagem.csv"
  intermediate_path: "data/interim/" 
  timegpt_fcst_file: "forecast_cache_fcst_y_validated_20240513_212354.pkl"
  timegpt_cache_prefix: "timegpt_forecast_cache"
  chronos_fcst_file: "chronos_forecast_cache_20240520_000009.pkl"
  chronos_cache_prefix: "chronos_forecast_cache"
  crop_target_datetime: "2021-01-01 00:00:00"
  default_seed: 42
model:
  context_window_len: 168
  forecast_len: 24
  batch_size: 32
  epochs: 500
  lr: 0.001
  beta: 0.5
  input_size: 1
  hidden_size: 64
  train_shuffle: true
  timegpt_finetune_steps: 0
  nixtla_api_key_path: "nixtla_api.key"
  chronos_finetune_steps: 0
  attempts_after_failure: 30
  device: "cuda"
  chronos_t5_model: "amazon/chronos-t5-large"